### ISSUE TITLE
Not working with Node 17+ due to crypto deprecations

### ISSUE THREAD

**Issue by rubenstolk** [Catbuttes/axios-ntlm#19]
Error: error:0308010C:digital envelope routines::unsupported

**Comment by vision10** [comment]
I have the same problem, but I dont know what to do abuut it
I will try updating the packages and hope it will be fixed with that

**Comment by rubenstolk** [comment]
I think there is no solution other than running Node with the `--openssl-legacy-provider` flag. NTLM apparently needs highly insecure `md4` and `md5` methods.

**Comment by rubenstolk** [comment]
Ideas welcome, I'd love to run without the flag...

**Comment by unilynx** [comment]
https://www.npmjs.com/package/js-md4 and https://www.npmjs.com/package/js-md5 exist. Could you fall back to those if openssl refuses to offer these algorithms?

(otherwise you'd have to convince the nodejs folks to force openssl to always make these algorithms available)

**Comment by rubenstolk** [comment]
We can replace `md4/md5` but I think the main issue is `DES-ECB`.

**Comment by unilynx** [comment]
> We can replace `md4/md5` but I think the main issue is `DES-ECB`.

Well there's https://www.npmjs.com/package/des.js too...  I'm currently trying to get it to work with axios-ntlm

**Comment by rubenstolk** [comment]
Nice - let me know if you find a solution.

**Comment by unilynx** [comment]
Here you go: https://github.com/Catbuttes/axios-ntlm/pull/21

It *should* be trivial to fix MD5 too, but the servers I'm talking to right now aren't triggering MD5 so I didn't want to do a blind fix

**Comment by unilynx** [comment]
Also, I've not attempted to do a graceful fallback (ie use the JS implementations of MD4/DES only if crypto doesn't support them). It's simpler this way and you shouldn't really use any of these algorithms anyway if you can avoid them, whether they're implemented in JS or C..

**Comment by rubenstolk** [comment]
Great. Now I just need to find a way to build it ;)

**Comment by unilynx** [comment]
as a shortterm fix you could just vendor & patch the reference to the ntlmClient - that's how i handled it for node-soap (as I had to patch that one too for other issues,  I didn't bother cleaning them up until seeing whether my PRs here and there are accepted: https://github.com/unilynx/node-soap/commit/f65d8df90644337e57cc116941832755a4a013d8 )

If it helps I've executed the build steps in this branch https://github.com/unilynx/axios-ntlm/tree/replace-and-build-libs

I do see some typescript errors when I build but they don't seem to be related to my changes and I doubt they ever passed

**Comment by skrtheboss** [comment]
I have created new npm packages, since i could not wait for this to be released.
| package                                                                                            | description                                                 |
| -------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [@node-ntlm/core](https://www.npmjs.com/package/@node-ntlm/core)       | Node.js NTLM utility package                                |
| [@node-ntlm/httpreq](https://www.npmjs.com/package/@node-ntlm/httpreq) | Node.js library to do HTTP NTLM authentication with httpreq ||
| [@node-ntlm/axios](https://www.npmjs.com/package/@node-ntlm/axios) | Node.js library to do HTTP NTLM authentication with axios |

Let me know if they work out for you, or if you have any suggestions/issues.

**Comment by unilynx** [comment]
1.4.0 got published and has the fixes. that resolve my issue for des-ecb and md4.

I presume md5 should be trivial to fix too the same way md4 got fixed (but none of the servers I'm speaking to required it, so I was unable to verify a fix)
